### ISSUE TITLE
TypeError: projects.map is not a function

### ISSUE THREAD

**Issue by supermafete** [takegue/bigquery-porter#8]
Hi there,

Trying out this tool, I'm experiencing the following error:

```
npx bqport pull --all --with-ddl @default
file:///Users/mfsimon/.nvm/versions/node/v16.18.0/lib/node_modules/bigquery-porter/dist/src/index.js:122
            await Promise.allSettled(projects.map(async (p) => await pullBigQueryResources({ projectId: p, ...options })));
                                              ^

TypeError: projects.map is not a function
    at Command.<anonymous> (file:///Users/mfsimon/.nvm/versions/node/v16.18.0/lib/node_modules/bigquery-porter/dist/src/index.js:122:47)
    at Command.listener [as _actionHandler] (/Users/mfsimon/.nvm/versions/node/v16.18.0/lib/node_modules/bigquery-porter/node_modules/commander/lib/command.js:482:17)
    at /Users/mfsimon/.nvm/versions/node/v16.18.0/lib/node_modules/bigquery-porter/node_modules/commander/lib/command.js:1264:65
    at Command._chainOrCall (/Users/mfsimon/.nvm/versions/node/v16.18.0/lib/node_modules/bigquery-porter/node_modules/commander/lib/command.js:1158:12)
    at Command._parseCommand (/Users/mfsimon/.nvm/versions/node/v16.18.0/lib/node_modules/bigquery-porter/node_modules/commander/lib/command.js:1264:27)
    at /Users/mfsimon/.nvm/versions/node/v16.18.0/lib/node_modules/bigquery-porter/node_modules/commander/lib/command.js:1062:27
    at Command._chainOrCall (/Users/mfsimon/.nvm/versions/node/v16.18.0/lib/node_modules/bigquery-porter/node_modules/commander/lib/command.js:1158:12)
    at Command._dispatchSubcommand (/Users/mfsimon/.nvm/versions/node/v16.18.0/lib/node_modules/bigquery-porter/node_modules/commander/lib/command.js:1058:23)
    at Command._parseCommand (/Users/mfsimon/.nvm/versions/node/v16.18.0/lib/node_modules/bigquery-porter/node_modules/commander/lib/command.js:1229:19)
    at Command.parse (/Users/mfsimon/.nvm/versions/node/v16.18.0/lib/node_modules/bigquery-porter/node_modules/commander/lib/command.js:890:10)
```

Node version: v16.18.0 (LTS)
System: MacOS Monterey
OAuth and default project configured via gcloud CLI.

**Comment by takegue** [comment]
Thank you for your reporting!
Could you try next command? I noticed that README.md is wrong.

```
npx bqport pull --all --with-ddl
```

**Comment by supermafete** [comment]
It works :)

Thank you.
